apiVersion: v1
kind: Namespace
metadata:
  name: focus
---
apiVersion: v1
kind: Service
metadata:
  name: focus
  namespace: focus
  labels:
    app: focus
spec:
  type: NodePort
  metadata:
    labels:
      app: focus
  ports:
    - name: http
      port: 80
      targetPort: 8082
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: focus
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: focus
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - focus
  selector:
    matchLabels:
      app: focus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: focus
  namespace: focus
spec:
  selector:
    matchLabels:
      app: focus
  replicas: 3
  template:
    metadata:
      labels:
        app: focus
    spec:
      containers:
      - name: focus
        image: registry.brotherlogic-backend.com/brotherlogic/focus-display:0.1.0 # {"$imagepolicy": "flux-system:focus"}
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
